version: "3.8"

services:
  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "${DB_PORT}:27017"
    volumes:
      - mongo_volume:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${DB_USERNAME}:${DB_ROOT_PASSWORD}@mongo:27017/
      ME_CONFIG_BASICAUTH: false
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      DB_PORT: ${DB_PORT}
      DB_ADDR: ${DB_ADDR}
      PORT: ${PORT}
      APP_ENV: ${APP_ENV}
      PROJECT_ID: ${PROJECT_ID}
      DEVELOPMENT_ENV: ${DEVELOPMENT_ENV}
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}
      APP_URL: ${APP_URL}
      SENDGRID_SENDER_EMAIL: ${SENDGRID_SENDER_EMAIL}
    depends_on:
      - mongo
    links:
      - mongo
volumes:
  mongo_volume:
