on:
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

name: release-plase

jobs:
  release-plase:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          release-type: simple
